### ISSUE TITLE
Strophe: TypeError: e.removeEventListener is not a function in example on detach track

### ISSUE THREAD

**Issue by dovalin** [jitsi/lib-jitsi-meet#1054]
## Description
I don't know if this is a bug or a problem with libs but i cannot find answer in community.
After deploying own instance of jitsi meet in vps and check it is working fine through UI (installed from debian packages).
I am trying to define a basic custom layout using this lib-jitsi-meet (https://meet.jit.si/libs/lib-jitsi-meet.min.js).
Custom html is launched in node: https://localhost:3000/index.html

Scripts loaded:
```
<script src="libs/jquery-2.1.1.min.js"></script>
<script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>
<script src="example.js" ></script>
```

## Current behavior

1) First user is launched and it is showed fine.
2) Second user is launched and it is showed fine (from another tab in same browser).
3) After closing second user I see in dev tools from first tab next error:

```
<Object.i.Strophe.log>:  Strophe: TypeError: e.removeEventListener is not a function
    at https://meet.jit.si/libs/lib-jitsi-meet.min.js:10:145235
    at Array.forEach (<anonymous>)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:10:145212)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:1:238623)
    at c.onUserLeft (https://localhost:3000/libjitsi/example.js:124:19)
    at c.emit (https://meet.jit.si/libs/lib-jitsi-meet.min.js:1:125694)
    at oe.onMemberLeft (https://meet.jit.si/libs/lib-jitsi-meet.min.js:10:176102)
```

L124 in example.js is detach call inside for:

```
function onUserLeft(id) {
    console.log('user left');
    if (!remoteTracks[id]) {
        return;
    }
    const tracks = remoteTracks[id];

    for (let i = 0; i < tracks.length; i++) {
        tracks[i].detach($(`#${id}${tracks[i].getType()}`));
    }
}
```

Options object is like:

```
const options = {
    hosts: {
        domain: baseDomain,
        muc: 'conference.' + baseDomain, // FIXME: use XEP-0030
    },
    serviceUrl: 'https://' + baseDomain + '/http-bind', // FIXME: use xep-0156 for that => UNCOMMENT FOR BOSH PROTOCOL
    //serviceUrl: 'wss://' + baseDomain + '/xmpp-websocket', // => UNCOMMENT FOR WSS

    // The name of client node advertised in XEP-0115 'c' stanza
    clientNode: 'http://jitsi.org/jitsimeet'
};
```

## Expected Behavior

Avoid this error.

## Possible Solution

Not provided

## Steps to reproduce

Launching example code.

# Environment details

Not needed.

Thanks in advance. Jitsi products looks like amazing.

**Comment by techcouncilbox** [comment]
sorry seems related to https://github.com/jitsi/lib-jitsi-meet/issues/859

**Comment by dovalin** [comment]
sorry seems related to https://github.com/jitsi/lib-jitsi-meet/issues/859
