### ISSUE TITLE
An error occurs with latest lib-jitsi-meet and new codec selection logic

### ISSUE THREAD

**Issue by bukharin** [jitsi/lib-jitsi-meet#1466]
Hi,

After updating `lib-jitsi-meet` we see new exceptions on Android devices. 

Stack trace:

```
Strophe: TypeError: Cannot read property 'split' of undefined
    at Object.parse (12-es2015.cd0f14ccf1feb8b710bd.js:1:685923)
    at A.getConfiguredVideoCodec (12-es2015.cd0f14ccf1feb8b710bd.js:1:573281)
    at R.setVideoCodecs (12-es2015.cd0f14ccf1feb8b710bd.js:1:237299)
    at u._selectPreferredCodec (12-es2015.cd0f14ccf1feb8b710bd.js:1:525353)
```

**Comment by damencho** [comment]
@jallamsetty1 ^ :)

**Comment by bukharin** [comment]
Problem exists not only on Android, but Chromium based. Top browsers:

![image](https://user-images.githubusercontent.com/3126568/105007194-7cf5ba00-5a59-11eb-9afc-209fb375700a.png)

**Comment by jallamsetty1** [comment]
@bukharin, thanks for the report, this seems to be because of a timing issue which I haven't encountered on the browsers I have tested. I will have a fix in shortly for this.
