### ISSUE TITLE
Can't load in svelte, window is not defined

### ISSUE THREAD

**Issue by ralyodio** [jitsi/lib-jitsi-meet#2061]
```
window is not defined
ReferenceError: window is not defined
    at d (/home/ettinger/www/grazily.com/grazily-ui/node_modules/lib-jitsi-meet/dist/lib-jitsi-meet.min.js:1:33)
    at /home/ettinger/www/grazily.com/grazily-ui/node_modules/lib-jitsi-meet/dist/lib-jitsi-meet.min.js:1:148
    at Object.<anonymous> (/home/ettinger/www/grazily.com/grazily-ui/node_modules/lib-jitsi-meet/dist/lib-jitsi-meet.min.js:1:270)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
```

Here is my code:

```
<script>
	import JitsiMeetJS from 'lib-jitsi-meet';
	import { onMount } from 'svelte';
	import { browser } from '$app/env';

	let connection;
	let room;

	function onConnectionSuccess() {
		console.log(arguments);
	}

	function onConnectionFailed() {
		console.error(arguments);
	}

	function disconnect() {
		console.log(arguments);
	}

	function onRemoteTrack() {
		console.log(arguments);
	}

	function onConferenceJoined() {
		console.log(arguments);
	}

	function onLocalTracks() {
		console.log(arguments);
	}

	function init() {
		JitsiMeetJS.init();
		const options = {};
		connection = new JitsiMeetJS.JitsiConnection(null, null, options);

		connection.addEventListener(
			JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED,
			onConnectionSuccess
		);
		connection.addEventListener(
			JitsiMeetJS.events.connection.CONNECTION_FAILED,
			onConnectionFailed
		);
		connection.addEventListener(JitsiMeetJS.events.connection.CONNECTION_DISCONNECTED, disconnect);

		room = connection.initJitsiConference('conference1', confOptions);
		room.on(JitsiMeetJS.events.conference.TRACK_ADDED, onRemoteTrack);
		room.on(JitsiMeetJS.events.conference.CONFERENCE_JOINED, onConferenceJoined);
		JitsiMeetJS.createLocalTracks().then(onLocalTracks);

		room.join();
	}

	onMount(async () => {
		if (browser) {
			init();
		}
	});
</script>

```

**Comment by ralyodio** [comment]
If I do an await import I get this error:

```
Uncaught (in promise) TypeError: global2 is undefined
```

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Take a look at the example how to use it
https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/example/index.html
https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/example/example.js
