### ISSUE TITLE
Multistream: replaceTrack failed when old track is null

### ISSUE THREAD

**Issue by DanielMcAssey** [jitsi/lib-jitsi-meet#2076]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
When attempting to replaceTrack a video track with no oldTrack set, I get a "replace track failed error". Further diagnosing, finds that the transceiver cannot be found when attempting a replace track in TPCUtils.js as currentDirection is never "inactive" and is always "recvonly".

The line that fails is this one: https://github.com/jitsi/lib-jitsi-meet/blob/6810839edc2cabc86ddd9163c724d8fee33b0ccd/modules/RTC/TPCUtils.js#L376

<details>
  <summary>Logs Snippet</summary>
```
lib-jitsi-meet.js:44665 2022-07-25T10:39:09.898Z [modules\RTC\TraceablePeerConnection.js] <TraceablePeerConnection.replaceTrack>:  TPC[id=1,type=JVB] TPC.replaceTrack using unified plan
lib-jitsi-meet.js:44665 2022-07-25T10:39:09.898Z [modules\RTC\TPCUtils.js] <TPCUtils.replaceTrack>: additional logging
	isNewLocalSource: true,
	mediaType: video,
	localTracks: [JitsiLocalTrack]0: JitsiLocalTrackaddEventListener: ƒ addListener(type, listener)audioLevel: -1conference: JitsiConference {connection: JitsiConnection, xmpp: XMPP, eventEmitter: EventEmitter, options: {…}, eventManager: JitsiConferenceEventManager, …}containers: []deviceId: "screen:3:0"disposed: falsehandlers: Map(0) {size: 0}maxEnabledResolution: 180metadata: {timestamp: 1658745532035}muteHandler: ƒ ()off: ƒ removeListener(type, listener)removeEventListener: ƒ removeListener(type, listener)resolution: 1080rtcId: 3sourceId: "screen:3:0"sourceType: "screen"storedMSID: "ed302c66-ed93-459d-9a08-f67162dc068e c4a5fa40-1948-4a76-8c58-0d72aad38643"stream: MediaStream {id: 'ed302c66-ed93-459d-9a08-f67162dc068e', active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}track: CanvasCaptureMediaStreamTrack {canvas: canvas, kind: 'video', id: 'e72273c3-0cf1-43e5-b605-45068a5ba213', label: 'HpnISuq8mjJm91otmHjloBml4JksqZaSDEz6MiNJCYxPn42ID6GlZzMN0Tjpybapud+FNdC4TMqw2G9d3t9aXQ==', enabled: true, …}type: "video"videoType: "desktop"_constraints: {deviceId: {…}, frameRate: {…}, height: {…}, width: {…}}_events: {track.trackMuteChanged: Array(2), track.videoTypeChanged: ƒ, track.audioLevelsChanged: ƒ, track.no_data_from_source: ƒ, track.streaming_status_changed: ƒ, …}_eventsCount: 6_facingMode: undefined_hasSentData: false_maxListeners: undefined_onDeviceListWillChange: devices => {…}_originalStream: MediaStream {id: '03515b57-cf2e-48d6-8dbb-f54943207cf6', active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}_prevSetMuted: ZoneAwarePromise {__zone_symbol__state: true, __zone_symbol__value: undefined}_realDeviceId: undefined_setEffectInProgress: false_sourceName: "fc41dbf5-v1"_streamEffect: PresenterEffect {renderer: BaseAnimationRenderer, desktopOverlayImage: undefined, renderDesktopOverlayScale: 1, outputCanvas: canvas, outputContext: CanvasRenderingContext2D, …}_streamInactiveHandler: () => {…}_testDataSent: true_trackEnded: false_trackMutedTS: 0[[Prototype]]: JitsiTracklength: 1,
	this.pc.peerconnection.getTransceivers(): [[Prototype]]: Array(0) (6) [RTCRtpTransceiver, RTCRtpTransceiver, RTCRtpTransceiver, RTCRtpTransceiver, RTCRtpTransceiver, RTCRtpTransceiver]
		0: RTCRtpTransceiver {mid: '0', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'sendrecv', …}currentDirection: "sendrecv"direction: "sendrecv"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (4) [{…}, {…}, {…}, {…}]mid: "0"receiver: RTCRtpReceiver {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, playoutDelayHint: null}sender: RTCRtpSender {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: RTCDTMFSender}stopped: false[[Prototype]]: RTCRtpTransceiver
		1: RTCRtpTransceiver {mid: '1', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'recvonly', …}currentDirection: "recvonly"direction: "recvonly"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]mid: "1"receiver: RTCRtpReceiver {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, playoutDelayHint: null}playoutDelayHint: nullrtcpTransport: nulltrack: MediaStreamTrackcontentHint: ""enabled: trueid: "21ba85a4-466c-4151-802c-cccdc22aac42"kind: "video"label: "21ba85a4-466c-4151-802c-cccdc22aac42"muted: trueoncapturehandlechange: nullonended: nullonmute: nullonunmute: nullreadyState: "live"[[Prototype]]: MediaStreamTracktransport: RTCDtlsTransport {iceTransport: RTCIceTransport, state: 'connected', onstatechange: ƒ, onerror: ƒ}[[Prototype]]: RTCRtpReceiversender: RTCRtpSender {track: null, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: null}stopped: false[[Prototype]]: RTCRtpTransceiver
		2: RTCRtpTransceiver {mid: '2', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'recvonly', …}currentDirection: "recvonly"direction: "recvonly"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (4) [{…}, {…}, {…}, {…}]mid: "2"receiver: RTCRtpReceiverplayoutDelayHint: nullrtcpTransport: nulltrack: MediaStreamTrack {__zone_symbol__mutefalse: Array(1), __zone_symbol__unmutefalse: Array(1), __zone_symbol__endedfalse: Array(1), kind: 'audio', id: 'b60a54aa-8fa4-47c0-8133-b0f3211cf75c-3', …}__zone_symbol__endedfalse: [ZoneTask]__zone_symbol__mutefalse: [ZoneTask]__zone_symbol__unmutefalse: [ZoneTask]contentHint: ""enabled: trueid: "b60a54aa-8fa4-47c0-8133-b0f3211cf75c-3"kind: "audio"label: "b60a54aa-8fa4-47c0-8133-b0f3211cf75c-3"muted: falseoncapturehandlechange: nullonended: nullonmute: nullonunmute: nullreadyState: "live"[[Prototype]]: MediaStreamTracktransport: RTCDtlsTransport {iceTransport: RTCIceTransport, state: 'connected', onstatechange: ƒ, onerror: ƒ}[[Prototype]]: RTCRtpReceiversender: RTCRtpSender {track: null, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: RTCDTMFSender}stopped: false[[Prototype]]: RTCRtpTransceiver
		3: RTCRtpTransceiver {mid: '3', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'recvonly', …}currentDirection: "recvonly"direction: "recvonly"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]mid: "3"receiver: RTCRtpReceiverplayoutDelayHint: nullrtcpTransport: nulltrack: MediaStreamTrack {__zone_symbol__mutefalse: Array(1), __zone_symbol__unmutefalse: Array(1), __zone_symbol__endedfalse: Array(1), kind: 'video', id: '7ffff572-1637-4ac9-a4be-962ab5fbb716-3', …}__zone_symbol__endedfalse: [ZoneTask]__zone_symbol__mutefalse: [ZoneTask]__zone_symbol__unmutefalse: [ZoneTask]contentHint: ""enabled: trueid: "7ffff572-1637-4ac9-a4be-962ab5fbb716-3"kind: "video"label: "7ffff572-1637-4ac9-a4be-962ab5fbb716-3"muted: falseoncapturehandlechange: nullonended: nullonmute: nullonunmute: nullreadyState: "live"[[Prototype]]: MediaStreamTracktransport: RTCDtlsTransport {iceTransport: RTCIceTransport, state: 'connected', onstatechange: ƒ, onerror: ƒ}[[Prototype]]: RTCRtpReceiversender: RTCRtpSender {track: null, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: null}stopped: false[[Prototype]]: RTCRtpTransceiver
		4: RTCRtpTransceiver {mid: '4', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'recvonly', …}currentDirection: "recvonly"direction: "recvonly"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]mid: "4"receiver: RTCRtpReceiver {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, playoutDelayHint: null}sender: RTCRtpSender {track: null, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: null}stopped: false[[Prototype]]: RTCRtpTransceiver
		5: RTCRtpTransceiver {mid: '5', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'sendrecv', …}currentDirection: "sendonly"direction: "sendrecv"headerExtensionsNegotiated: (2) [{…}, {…}]headerExtensionsToOffer: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]mid: "5"receiver: RTCRtpReceiver {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, playoutDelayHint: null}sender: RTCRtpSender {track: CanvasCaptureMediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, dtmf: null}stopped: false[[Prototype]]: RTCRtpTransceiverlength: 6[[Prototype]]: Array(0)
lib-jitsi-meet.js:44665 2022-07-25T10:39:09.901Z [modules\xmpp\JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=egil05p0dsf1t] Replace track error: Error: replace track failed
    at TPCUtils.replaceTrack (lib-jitsi-meet.js:11869:29)
    at TraceablePeerConnection.replaceTrack (lib-jitsi-meet.js:13970:41)
    at workFunction (lib-jitsi-meet.js:38736:27)
    at AsyncQueue._processQueueTasks (lib-jitsi-meet.js:32357:7)
    at lib-jitsi-meet.js:71339:9
    at Object.process (lib-jitsi-meet.js:69002:17)
    at lib-jitsi-meet.js:68860:19
    at lib-jitsi-meet.js:67402:41
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26339:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
lib-jitsi-meet.js:44665 2022-07-25T10:39:09.903Z [JitsiConference.js] replaceTrack failed: Error: replace track failed
    at TPCUtils.replaceTrack (http://localhost:4200/421.js:38944:39)
    at TraceablePeerConnection.replaceTrack (http://localhost:4200/421.js:41190:51)
    at workFunction (http://localhost:4200/421.js:68752:37)
    at AsyncQueue._processQueueTasks (http://localhost:4200/421.js:61669:17)
    at http://localhost:4200/421.js:103912:15
    at Object.process (http://localhost:4200/421.js:101489:19)
    at http://localhost:4200/421.js:101325:21
    at http://localhost:4200/421.js:99820:49
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:19416:171)
    at Object.onInvokeTask (http://localhost:4200/main.js:208367:25)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:19416:54)
    at Zone.runTask (http://localhost:4200/polyfills.js:19177:37)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:19625:23)
conference-manager.service.ts:1498 failed to replace video input device Error: replace track failed
    at TPCUtils.replaceTrack (lib-jitsi-meet.js:11869:29)
    at TraceablePeerConnection.replaceTrack (lib-jitsi-meet.js:13970:41)
    at workFunction (lib-jitsi-meet.js:38736:27)
    at AsyncQueue._processQueueTasks (lib-jitsi-meet.js:32357:7)
    at lib-jitsi-meet.js:71339:9
    at Object.process (lib-jitsi-meet.js:69002:17)
    at lib-jitsi-meet.js:68860:19
    at lib-jitsi-meet.js:67402:41
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26339:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
```
</details>

## Current behavior
---
When no camera is selected, attempt to replace track, it does not add the track to the conference and fails with an error.
## Expected Behavior
---
When no camera is selected, attempt to replace track with a new camera track and it should appear to all participants.
## Possible Solution
---
Not sure, but could it be possible Chrome has changed functionality on how currentDirection is expected to be set?
## Steps to reproduce
---
1. Start with no camera track and multistream/source-signalling enabled
2. Create a new camera track without adding it to the room
3. Call replaceTrack with first argument null (oldTrack) and second argument the new track that was just created
# Environment details
---
Custom app
Electron: 19.0.8
Chrome: 102.0.5005.148
Conference services: Latest docker-jitsi-meet stable version

**Comment by zsinba** [comment]
how about it

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
@DanielMcAssey Is this the first time you are adding the track to the conference ? If that is the case, you need to use JitsiConference.addTrack() instead of calling replaceTrack. Can you check if this fixes your issue ?

**Comment by DanielMcAssey** [comment]
@jallamsetty1 Yep that seems to have resolved it, not sure if its worth a comment on the replaceTrack function, as pre-multistream the replaceTrack method would work if the oldTrack was null.

**Comment by jallamsetty1** [comment]
I agree, I will update the documentation. Pre-multistream, we could use both addTrack and replaceTrack for adding the track for the first time but with multi-stream every new source needs to be added to the conference first using addTrack and then replaceTrack can be used to change tracks for that given source.
