### ISSUE TITLE
Unable to build with node 18.2.0

### ISSUE THREAD

**Issue by xXTraceXx** [jitsi/lib-jitsi-meet#2131]
## Description
I tried to build this project with node version 18.2.0 (`npm run build`) and ran into the following error:

```
 Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/mnt/d/lib-jitsi-meet/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/mnt/d/lib-jitsi-meet/node_modules/webpack/lib/util/createHash.js:80:21)
    at /mnt/d/lib-jitsi-meet/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next31 (eval at create (/mnt/d/lib-jitsi-meet/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next9 (eval at create (/mnt/d/lib-jitsi-meet/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/mnt/d/lib-jitsi-meet/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:119:1)
    at Hook.CALL_DELEGATE [as _call] (/mnt/d/lib-jitsi-meet/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/mnt/d/lib-jitsi-meet/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
---

## Current behavior
Unable to build project (lib-jitsi-meet.min.js)
---

## Expected Behavior
Able to build project
---

## Possible Solution
After some research i found the problem. Node v17 has a new feature for OpenSSL 3.0 and an article describing the problem (https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382 headline OpenSSL 3.0)

I found the solution in stackoverflow:
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported (NODE_OPTIONS=--openssl-legacy-provider)
---

## Steps to reproduce
---
install node 17 or higher and ran `npm run build`

# Environment details
---
node v18.2.0

**Comment by saghul** [comment]
We only test and deploy with LTS, that is Node 16 at the moment.

**Comment by jakub-g** [comment]
FWIW Node 18 is the LTS now.

The issue is due to outdated webpack. You need at least 5.61.0 to support node 17+ by default.
