### ISSUE TITLE
Unable to join a room with latest build lib-jitsi-meet

### ISSUE THREAD

**Issue by xXTraceXx** [jitsi/lib-jitsi-meet#2203]
## Description
---
I cloned lib-jitsi-meet repo and ran `npm install` and `npm run build` with `node version v16.15.0`. I got a `dist` (umd + esm). I used the example from lib-jitsi-meet repo and replaced the lib-jitsi-meet script, with my own that i build before.

## Current behavior
---
Getting error:
Logger.js:154 2023-01-11T14:43:27.892Z [modules/xmpp/moderator.js] <Ir._handleError>:  Failed to get a successful response, giving up. Error: Failed to get a successful response, giving up.
    at Ir._handleError (moderator.js:388:23)
    at Ir._handleIqError (moderator.js:437:10)
    at moderator.js:266:31
    at P.Handler.handler (strophe.umd.js:2716:25)
    at P.Handler.run (strophe.umd.js:1875:33)
    at strophe.umd.js:3157:35
    at Object.forEachChild (strophe.umd.js:830:21)
    at P.Connection._dataRecv (strophe.umd.js:3146:25)
    at N.Bosh._onRequestStateChange (strophe.umd.js:5012:19)

## Expected Behavior
---
Should join room as expected.

## Reproduce Error
See project in my repo: 
https://github.com/xXTraceXx/Jitsi-Error

**Comment by Zaid5775** [comment]
can i work on this issue @xXTraceXx ?

**Comment by damencho** [comment]
> Same here, on FreeBSD 13.2 and Jitsi Meet version 1.0.6991

Most probably you have a problem with the configuration. Not sure how you installed and configured, but have you configured the client proxy and updated its roster?
https://github.com/jitsi/jitsi-meet/blob/609942654a3a892474f56b2e837ce3552092855a/debian/jitsi-meet-prosody.postinst#L213

**Comment by philipp-durrer-jarowa** [comment]
(How) Does this command get executed when using the upstream prosody docker image? We face the same errors, every 3rd or so connect to the k8s jitsi deployment fails with this error when the user is clicking "Join conference" and the error appears immediately.
