### ISSUE TITLE
Cannot join a conference room. room.selectParticipants (in onUserJoined method) gives an error.

### ISSUE THREAD

**Issue by yash-vardhan-github** [jitsi/lib-jitsi-meet#2236]
I have used the same code given in the 'ljm-jaas-example' repo and I cannot join a conference room. The following gets logged to the console whenever a participant joins. However, the same code used to work until two days back from now (18th Jan 2023).

2023-03-18T06:33:01.335Z [modules/xmpp/strophe.util.js] <Sa.vt.Strophe.log>:  Strophe: TypeError: room.selectParticipants is not a function
    at r.onUserJoined (file:///C:/Users/yvard/Desktop/ljm-jaas-example-master/ljm-jaas-example-master/example.js:179:10)
    at r.emit (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:82371)
    at Zu.onMemberJoined (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:773810)
    at r.emit (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:82314)
    at Nr.onPresence (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:426068)
    at Lr.onPresence (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:442099)
    at P.Handler.run (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:222036)
    at https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:230474
    at Object.forEachChild (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:213704)
    at P.Connection._dataRecv (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:230323)
    at N.Websocket._onMessage (https://meet.jit.si/libs/lib-jitsi-meet.min.js:2:259553)

**Comment by saghul** [comment]
We need to update the example. /cc @jallamsetty1

**Comment by jallamsetty1** [comment]
The example was using a deprecated API that was removed in the last release. The sample has been updated to use the new API for requesting all videos from the bridge. Fixed in https://github.com/jitsi/ljm-jaas-example/pull/4
