### ISSUE TITLE
Running the project in xcode ios

### ISSUE THREAD

**Issue by NipunBilala** [jitsi/lib-jitsi-meet#673]
as i run the app it compiles but i see a red screen with the following error.

Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified]  11.4% (322/952), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `/Users/dil-macmini2/Downloads/jitsi-meet-master/react/features/base/lib-jitsi-meet/_.native.js`: Module does not exist in the module map

**Comment by saghul** [comment]
Have you installed all JavaScript dependencies?

**Comment by NipunBilala** [comment]
Yes i have , Now i am able to build the project but facing new issue now .
Attached is the error i am getting please guide me how to resolve it.
![simulator screen shot - iphone 8 - 2017-12-19 at 12 40 07](https://user-images.githubusercontent.com/15031428/34144920-c7c38d0a-e4b9-11e7-99e2-63f9b32b98c4.png)



Following is the terminal output

Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified]  99.8% (947/948), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `/Users/dil-macmini2/Downloads/jitsi-meet-master/react/features/base/lib-jitsi-meet/_.native.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:292:11)
    at ModuleResolution.tryResolveSync (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:16)
    at Object.tryResolveSync (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:118:12)
    at ResolutionRequest.resolveDependency (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:100:39)
    at dependencyNames.map.name (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:133:42)
    at module.readFresh.then (/Users/dil-macmini2/Downloads/jitsi-meet-master/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:181:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by saghul** [comment]
Can you please write down the steaps you're following and what versions of Node and npm you are using? Thanks!

**Comment by jorgearreola** [comment]
Hi! i have the same issue, Any idea? TKS!!!

**Comment by jorgearreola** [comment]
Tks for response @saghul  !!!

macOS 10.13.4 (compile in Xcode) 
node v8.11.4
npm v 6.4.0

I installed the dependencies and build the project with jitsimeet  sdk, but when running the app I have the following error:

<img width="374" alt="captura de pantalla 2018-08-22 a la s 14 35 50" src="https://user-images.githubusercontent.com/10789496/44486284-c2a7c180-a618-11e8-9a55-4dac7711436b.png">

wha's wrong? 

TKS for your help!!!!!!

**Comment by saghul** [comment]
Are you building your own project with the Jitsi Meet SDK or are you building Jitsi Meet itself?

**Comment by jorgearreola** [comment]
I building Jitsi Meet itself for test @saghul

**Comment by saghul** [comment]
Hum, did you run the suggested commands? (remove node_modules, clear watchman and reinstall)

**Comment by jorgearreola** [comment]
Hi @saghul, I solved the problem ... it was a mistake in npm install !!!

thank you very much dude!!!!!

**Comment by saghul** [comment]
Glad to hear! I’m going to close this then.

**Comment by nileshmean** [comment]
Still getting same error 
error: bundling failed: Error: Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `react/features/base/lib-jitsi-meet/_.native.js`: lib-jitsi-meet/lib-jitsi-meet.min could not be found within the project.

**Comment by asad175** [comment]
The solution is very simple. I have shared it here in my article. [Solution: Unable to resolve module lib-jitsi-meet/lib-jitsi-meet.min](https://handyopinion.com/unable-to-resolve-module-lib-jitsi-meet-lib-jitsi-meet-min/) .
We just need to go inside "lib-jitsi-meet" directory and need to run yarn command.
