### ISSUE TITLE
"No participant for id" after removing track

### ISSUE THREAD

**Issue by webdif** [jitsi/lib-jitsi-meet#859]
## Description
I have a webapp with one publisher and one subscriber.
1. After creating connection (`JitsiMeetJS.JitsiConnection`).
2. We get publisher devices (`createLocalTracks`).
3. And we add these local tracks to the conference room (`room.addTrack(track)`).
4. Subscriber is listening to events (`TRACK_ADDED`, `TRACK_REMOVED`).
5. When publisher load the webapp, the subscriber receives and diplays the tracks. It works.
6. When publisher close his browser window, this subscriber removes the tracks. It works.

## Current behavior
An error like this comes up at step 6:
```
[modules/connectivity/ParticipantConnectionStatus.js] <ParticipantConnectionStatusHandler.onTrackRtcMuted>:  No participant for id: oq0jzywf
```

## Expected Behavior
The track should be removed without errors.

## Possible solution
No idea, but the app seems to try muting track, I don't know why.
The error come from `_onTrackMute()`.

```js
  _createClass(JitsiRemoteTrack, [{
    key: "_bindMuteHandlers",
    value: function _bindMuteHandlers() {
      var _this2 = this;

      this.track.addEventListener('mute', function () {
        >>> return _this2._onTrackMute();
      });
      this.track.addEventListener('unmute', function () {
        return _this2._onTrackUnmute();
      });
    }
```

## Environment details
React app on macOS.

---

Thanks a lot for your help 🙂 
And congrats for this lib 👏

**Comment by Jip-Hop** [comment]
I encounter this issue as well when running `lib-jitsi-meet/doc/example/index.html`.
Is there already a fix for this?

```
2019-10-25T11:34:45.021Z [modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: TypeError: e.removeEventListener is not a function
    at https://meet.jit.si/libs/lib-jitsi-meet.min.js:22:70940
    at Array.forEach (<anonymous>)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:22:70917)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:235385)
    at c.onUserLeft (file:///Users/user/Downloads/lib-jitsi-meet-jitsi-meet_4021/doc/example/example.js:123:19)
    at c.emit (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:147431)
    at Y.onMemberLeft (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:294818)
    at c.emit (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:147431)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:15:70070)
    at t.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:15:71243)
    at s.value (https://meet.jit.si/libs/lib-jitsi-meet.min.js:15:59171)
    at r.Handler.run (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:21541)
    at https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:29869
    at Object.forEachChild (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:13309)
    at r.Connection._dataRecv (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:29701)
    at e.Bosh._onRequestStateChange (https://meet.jit.si/libs/lib-jitsi-meet.min.js:6:49373)

2019-10-25T11:34:45.023Z [modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: error: e.removeEventListener is not a function

2019-10-25T11:34:45.103Z [modules/connectivity/ParticipantConnectionStatus.js] <e.value>:  No participant for id: 8f4b6499
```

**Comment by zsinba** [comment]
我也遇到这个情况。
但并不耽误运行

**Comment by jessicanevesmachado** [comment]
hello, I have the same error, is there a solution?

**Comment by sapkra** [comment]
@saghul This error is also occurring on meet.jit.si. Do you have an idea how to fix it?

**Comment by Shotster** [comment]
Just wanted to +1 this issue, as I'm seeing it as well - on both a custom integration using the Jitsi Lib API as well as on meet.jit.si when using the web interface, as @sapkra mentioned. It seems benign - i.e. no ill effects aside from the red text in the console - but it would be nice to resolve it. 😉

**Comment by Boby** [comment]
+1 on this, and I got disconnected every 20mins because of this error, anyway to fix on this?
