### ISSUE TITLE
ERROR in lib-jitsi-meet.min.js from Terser  Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by tiofabby** [jitsi/lib-jitsi-meet#866]
Hi,
Since today, compilation of lib-jitsi-meet is failing with following error:
In my package.json I have following version:
`"lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#0664db2",`

and I am doing in node_modules/lib-jitsi-meet:
`npm install & npm run postinstall`

here are the logs:

```
+ lib-jitsi-meet@0.0.0
updated 1 package and audited 16704 packages in 22.234s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
> git-validate@2.2.4 install /Users/...../node_modules/lib-jitsi-meet/node_modules/git-validate
> node bin/install
> fsevents@1.2.7 install /Users/....../node_modules/lib-jitsi-meet/node_modules/fsevents
> node install
node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/..../node_modules/lib-jitsi-meet/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
> precommit-hook@3.0.0 install /Users/...../node_modules/lib-jitsi-meet/node_modules/precommit-hook
> node bin/install
> lib-jitsi-meet@0.0.0 postinstall /Users/...../node_modules/lib-jitsi-meet
> webpack -p

Hash: 1ddf5f3b04013fa9778a
Version: webpack 4.26.1
Child
    Hash: 1ddf5f3b04013fa9778a
    Time: 6785ms
    Built at: 04/02/2019 11:55:23
     2 assets
    Entrypoint lib-jitsi-meet = lib-jitsi-meet.min.js lib-jitsi-meet.min.map
      [2] ./JitsiConferenceEvents.js 8.21 KiB {0} [built]
      [3] ./modules/browser/index.js 98 bytes {0} [built]
      [6] ./modules/statistics/statistics.js 28.1 KiB {0} [built]
      [7] ./service/statistics/AnalyticsEvents.js 15 KiB {0} [built]
      [9] ./service/RTC/MediaType.js 110 bytes {0} [built]
     [10] ./modules/util/GlobalOnErrorHandler.js 2.37 KiB {0} [built]
     [12] ./JitsiTrackErrors.js 2.68 KiB {0} [built]
     [13] ./modules/RTC/RTC.js 34.3 KiB {0} [built]
     [15] ./JitsiTrackError.js 6.07 KiB {0} [built]
     [17] ./JitsiTrackEvents.js 1.31 KiB {0} [built]
     [20] ./modules/videosipgw/VideoSIPGWConstants.js 1.44 KiB {0} [built]
     [21] ./JitsiConferenceErrors.js 2.12 KiB {0} [built]
     [22] ./JitsiConnectionEvents.js 1.44 KiB {0} [built]
    [119] ./index.js 160 bytes {0} [built]
    [120] ./JitsiMeetJS.js 19.4 KiB {0} [built]
        + 140 hidden modules

    ERROR in lib-jitsi-meet.min.js from Terser
    TypeError: Cannot read property 'minify' of undefined
        at minify (/Users/...../node_modules/lib-jitsi-meet/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
        at module.exports (/Users/...../node_modules/lib-jitsi-meet/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
        at handle (/Users/...../node_modules/lib-jitsi-meet/node_modules/worker-farm/lib/child/index.js:44:8)
        at process.<anonymous> (/Users/...../node_modules/lib-jitsi-meet/node_modules/worker-farm/lib/child/index.js:51:3)
        at process.emit (events.js:182:13)
        at emit (internal/child_process.js:811:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! Exit status 2 

```
Any help would be greatly appreciated!!
Thank you
Fabrice

**Comment by tiofabby** [comment]
Building issue is not happening anymore now...
Not sure what happened and what has been changed..
Closing as I cannot reproduce anymore...
